//instancetype = "t2.micro"
//keypair      = "for-tomcat"
//vpc-cidr     = "10.0.0.0/16"
//azs          = "us-east-1a"
//KeyName      = "~/.ssh/id_rsa.pub"
//UserData     = "shellscript.sh"
//region       = "us-east-1"